repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: ruff-format
        name: ruff format
        entry: ruff format .
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: mypy
        name: mypy
        entry: mypy raglan/ --ignore-missing-imports
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest
        entry: pytest tests/ -n auto -k "not slow"
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
