"""End-to-end pipeline test using pre-computed embeddings (no model, no network).

Loads fixture files generated by ``tests/generate_e2e_fixtures.py``, inserts
into pgvector / ChromaDB / Qdrant, and runs semantic search queries with
pre-computed query embeddings and variants.

Run::

    pytest tests/test_e2e_precomputed.py -v -s
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import os
import shutil
import tempfile
import uuid
from pathlib import Path

import pytest

pytestmark = [pytest.mark.integration]

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"

# Unique suffix for xdist parallel workers (avoids table collisions)
_WORKER = os.environ.get("PYTEST_XDIST_WORKER", "").replace("gw", "w")
_TABLE = f"e2e_chunks{_WORKER}"


def _load_json(name: str) -> list[dict]:
    path = FIXTURES_DIR / name
    if not path.exists():
        pytest.skip(f"Fixture {name} not found — run: python tests/generate_e2e_fixtures.py")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


# ============================================================================
# Shared fixture — load pre-computed data once per session
# ============================================================================


@pytest.fixture(scope="session")
def e2e_fixtures():
    """Load pre-computed chunks and queries from JSON (no model needed)."""
    chunks = _load_json("e2e_chunks.json")
    queries = _load_json("e2e_queries.json")
    return {"chunks": chunks, "queries": queries}


# ============================================================================
# pgvector
# ============================================================================


async def _pg_connect():
    import asyncpg

    candidates = [
        os.environ.get("RAGLAN_PGCONN"),
        "postgresql://postgres:postgres@localhost:5432/raglan_test",
        "postgresql://postgres:123456@localhost:5432/raglan_test",
    ]
    for cs in candidates:
        if cs is None:
            continue
        try:
            return await asyncpg.create_pool(cs, min_size=1, max_size=2, command_timeout=10)
        except Exception:
            pass
    return None


async def _pg_setup(pool, chunks):
    await pool.execute("CREATE EXTENSION IF NOT EXISTS vector")
    await pool.execute(f"DROP TABLE IF EXISTS {_TABLE}")
    await pool.execute(
        f"CREATE TABLE {_TABLE} ("
        "  chunk_id TEXT PRIMARY KEY,"
        "  parent_id TEXT NOT NULL DEFAULT '',"
        "  content TEXT NOT NULL,"
        "  embedding vector(384),"
        "  metadata JSONB DEFAULT '{}'"
        ")"
    )
    for c in chunks:
        emb_str = "[" + ",".join(f"{x:.8g}" for x in c["embedding"]) + "]"
        await pool.execute(
            f"INSERT INTO {_TABLE} VALUES ($1,$2,$3,$4::vector,$5::jsonb)",
            c["chunk_id"],
            c["parent_id"],
            c["content"],
            emb_str,
            json.dumps(c["metadata"]),
        )
    await pool.execute(
        f"CREATE INDEX IF NOT EXISTS e2e_idx ON {_TABLE} "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 1)"
    )


async def _pg_search(pool, embedding, top_k=5):
    emb_str = "[" + ",".join(f"{x:.8g}" for x in embedding) + "]"
    rows = await pool.fetch(
        f"SELECT chunk_id, content, metadata, parent_id, "
        f"1 - (embedding <=> $1::vector) AS score "
        f"FROM {_TABLE} ORDER BY embedding <=> $1::vector LIMIT $2",
        emb_str,
        top_k,
    )
    results = []
    for r in rows:
        meta = r[2] if isinstance(r[2], dict) else json.loads(r[2])
        meta["parent_id"] = r[3]
        results.append(
            {"chunk_id": r[0], "content": r[1][:120], "metadata": meta, "score": float(r[4])}
        )
    return results


class TestPgvectorPrecomputed:
    @pytest.fixture
    async def pg_pool(self, e2e_fixtures):
        pool = await _pg_connect()
        if pool is None:
            pytest.skip("PostgreSQL not available")
        try:
            await pool.execute("CREATE EXTENSION IF NOT EXISTS vector")
        except Exception as e:
            if "duplicate key" not in str(e) and "already exists" not in str(e):
                raise
        await pool.execute(f"DROP TABLE IF EXISTS {_TABLE}")
        await pool.execute(
            f"CREATE TABLE {_TABLE} ("
            "  chunk_id TEXT PRIMARY KEY,"
            "  parent_id TEXT NOT NULL DEFAULT '',"
            "  content TEXT NOT NULL,"
            "  embedding vector(384),"
            "  metadata JSONB DEFAULT '{}'"
            ")"
        )
        for c in e2e_fixtures["chunks"]:
            emb_str = "[" + ",".join(f"{x:.8g}" for x in c["embedding"]) + "]"
            await pool.execute(
                f"INSERT INTO {_TABLE} VALUES ($1,$2,$3,$4::vector,$5::jsonb)",
                c["chunk_id"],
                c["parent_id"],
                c["content"],
                emb_str,
                json.dumps(c["metadata"]),
            )
        yield pool
        await pool.execute(f"DROP TABLE IF EXISTS {_TABLE}")
        await pool.close()

    @pytest.mark.asyncio
    @pytest.mark.parametrize("q", range(7))
    async def test_search(self, pg_pool, e2e_fixtures, q):
        query_data = e2e_fixtures["queries"][q]
        results = await _pg_search(pg_pool, query_data["embedding"], top_k=3)
        assert len(results) >= 1, f"No results for '{query_data['label']}'"
        assert results[0]["score"] > 0

    @pytest.mark.asyncio
    async def test_variant_search(self, pg_pool, e2e_fixtures):
        """Each query variant should also return relevant results."""
        query_data = e2e_fixtures["queries"][0]  # "chunking strategies"
        for i, vemb in enumerate(query_data["variant_embeddings"]):
            results = await _pg_search(pg_pool, vemb, top_k=3)
            assert len(results) >= 1, f"Variant {i} of '{query_data['label']}' got no results"

    @pytest.mark.asyncio
    async def test_parent_child_links(self, pg_pool, e2e_fixtures):
        """Child chunks reference their parent via parent_id."""
        query_data = e2e_fixtures["queries"][1]  # "embedding models"
        results = await _pg_search(pg_pool, query_data["embedding"], top_k=5)
        children = [r for r in results if r["metadata"].get("type") == "child"]
        assert len(children) >= 1
        for c in children:
            assert c["metadata"].get("parent_id", "").startswith("parent_")


# ============================================================================
# ChromaDB
# ============================================================================


def _chroma_setup(chunks):
    import chromadb

    client = chromadb.Client()
    with contextlib.suppress(Exception):
        client.delete_collection("e2e_raglan")
    col = client.create_collection("e2e_raglan", metadata={"hnsw:space": "cosine"})

    ids = [c["chunk_id"] for c in chunks]
    docs = [c["content"] for c in chunks]
    embs = [c["embedding"] for c in chunks]
    metas = [{**c["metadata"], "parent_id": c["parent_id"]} for c in chunks]

    for i in range(0, len(ids), 100):
        col.add(
            ids=ids[i : i + 100],
            documents=docs[i : i + 100],
            embeddings=embs[i : i + 100],
            metadatas=metas[i : i + 100],
        )
    return client


def _chroma_search(client, embedding, top_k=5):
    col = client.get_collection("e2e_raglan")
    resp = col.query(query_embeddings=[embedding], n_results=top_k)
    results = []
    if resp["ids"] and resp["ids"][0]:
        for i, cid in enumerate(resp["ids"][0]):
            dist = resp["distances"][0][i] if resp["distances"] else 0.0
            results.append(
                {
                    "chunk_id": cid,
                    "content": (resp["documents"][0][i] if resp["documents"] else "")[:120],
                    "metadata": resp["metadatas"][0][i] if resp["metadatas"] else {},
                    "score": round(1.0 - dist / 2.0, 4),
                }
            )
    return results


class TestChromaDBPrecomputed:
    @pytest.fixture
    def chroma_client(self, e2e_fixtures):
        return _chroma_setup(e2e_fixtures["chunks"])

    @pytest.mark.parametrize("q", range(7))
    def test_search(self, chroma_client, e2e_fixtures, q):
        query_data = e2e_fixtures["queries"][q]
        results = _chroma_search(chroma_client, query_data["embedding"], top_k=3)
        assert len(results) >= 1, f"No results for '{query_data['label']}'"
        assert results[0]["score"] > 0


# ============================================================================
# Qdrant
# ============================================================================


async def _qdrant_setup(chunks):
    from qdrant_client import AsyncQdrantClient
    from qdrant_client.models import Distance, PointStruct, VectorParams

    tmpdir = tempfile.mkdtemp(prefix="raglan_qdrant_")
    client = AsyncQdrantClient(path=tmpdir)
    await client.create_collection(
        "e2e_raglan",
        vectors_config=VectorParams(size=384, distance=Distance.COSINE),
    )

    ns = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")
    points = []
    for c in chunks:
        points.append(
            PointStruct(
                id=str(uuid.uuid5(ns, c["chunk_id"])),
                vector=c["embedding"],
                payload={
                    "chunk_id": c["chunk_id"],
                    "parent_id": c["parent_id"],
                    "content": c["content"][:500],
                    "type": c["metadata"].get("type", ""),
                    "heading": c["metadata"].get("heading", ""),
                },
            )
        )
    await client.upsert("e2e_raglan", points)
    await client.close()
    return tmpdir


async def _qdrant_search(qdrant_path, embedding, top_k=5):
    from qdrant_client import AsyncQdrantClient
    from qdrant_client.models import NearestQuery

    client = AsyncQdrantClient(path=qdrant_path)
    resp = await client.query_points(
        "e2e_raglan",
        query=NearestQuery(nearest=embedding),
        limit=top_k,
        with_payload=True,
    )
    await client.close()
    results = []
    for p in resp.points:
        pl = p.payload or {}
        results.append(
            {
                "chunk_id": pl.get("chunk_id", str(p.id)),
                "content": pl.get("content", "")[:120],
                "metadata": {
                    "type": pl.get("type", ""),
                    "heading": pl.get("heading", ""),
                    "parent_id": pl.get("parent_id", ""),
                },
                "score": round(p.score or 0.0, 4),
            }
        )
    return results


class TestQdrantPrecomputed:
    @pytest.fixture
    def qdrant_path(self, e2e_fixtures):
        path = asyncio.run(_qdrant_setup(e2e_fixtures["chunks"]))
        yield path
        shutil.rmtree(path, ignore_errors=True)

    @pytest.mark.asyncio
    @pytest.mark.parametrize("q", range(7))
    async def test_search(self, qdrant_path, e2e_fixtures, q):
        query_data = e2e_fixtures["queries"][q]
        results = await _qdrant_search(qdrant_path, query_data["embedding"], top_k=3)
        assert len(results) >= 1, f"No results for '{query_data['label']}'"
        assert results[0]["score"] > 0


# ============================================================================
# Cross-backend consistency
# ============================================================================


class TestCrossBackendConsistency:
    @pytest.fixture
    async def all_backends(self, e2e_fixtures):
        """Set up all three backends once (per-test for event loop safety)."""
        pool = await _pg_connect()
        if pool:
            await _pg_setup(pool, e2e_fixtures["chunks"])
        chroma = _chroma_setup(e2e_fixtures["chunks"])
        qdrant_path = await _qdrant_setup(e2e_fixtures["chunks"])
        yield {"pg": pool, "chroma": chroma, "qdrant_path": qdrant_path}
        if pool:
            await pool.execute(f"DROP TABLE IF EXISTS {_TABLE}")
            await pool.close()
        shutil.rmtree(qdrant_path, ignore_errors=True)

    @pytest.mark.asyncio
    async def test_top_results_overlap(self, all_backends, e2e_fixtures):
        """All three backends should agree on the best match."""
        query_data = e2e_fixtures["queries"][0]  # chunking strategies
        emb = query_data["embedding"]

        pg_ids = {r["chunk_id"] for r in await _pg_search(all_backends["pg"], emb, 3)}
        ch_ids = {r["chunk_id"] for r in _chroma_search(all_backends["chroma"], emb, 3)}
        qd = await _qdrant_search(all_backends["qdrant_path"], emb, 3)
        qd_ids = {r["chunk_id"] for r in qd}

        assert pg_ids & ch_ids, "pgvector and chromadb have no overlap"
        assert pg_ids & qd_ids, "pgvector and qdrant have no overlap"
        print(f"\n  pgvector: {pg_ids}\n  chromadb: {ch_ids}\n  qdrant:   {qd_ids}")
